### ISSUE TITLE
H.Recorders.NAudioRecorder causes failed build 'IRecorder does not contain definition RawDataReceived' 

### ISSUE THREAD

**Issue by Michael-Kempe** [HavenDV/H.ProxyFactory#6]
Hi, I'm trying to compile and run H.ProxyFactory.Apps.Wpf but I got some compile errors saying 'IRecorder does not contain some definitions. (RawDataReceived, InitializeAsync and StopAsync) and I don't know how to fix this.

Maybe someone can give me a hint? I would welcome it!

**Comment by HavenDV** [comment]
Hello. I understand you have updated NuGet packages before launch.
I removed this dependency, please download the new version. I updated all NuGet packages to the new version.
I'll clarify - for correct testing of the application, at the moment it is required to launch TWO processes. This will not work within a single process.

**Comment by Michael-Kempe** [comment]
Thanks. Now I can build it.
When I extending the interface _ISimpleEventClass_ (used inside your Wpf App) with the following new Method: 
List<string> Method3(); and return some random data from this method, the client returns an Exception saying:
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Collections.Generic.List`1[System.String]'.
   at ISimpleEventClass_ProxyType_23cedf31-bec6-4722-91d4-3b324026e3dd.Method3()
   at H.ProxyFactory.Apps.Wpf.ClientWindow.Method3Button_Click(Object sender, RoutedEventArgs e) in F:\Temp\H.ProxyFactory-master\src\apps\H.ProxyFactory.Apps.Wpf\ClientWindow.xaml.cs:line 173

![image](https://user-images.githubusercontent.com/46563088/150106124-6bb93c0d-fb35-497d-a672-03b255ce4824.png)

Is List<<T>> supported?

**Comment by HavenDV** [comment]
I don't actively use this library in my projects, so yes, it's possible that it's not supported. I think if you change the return type to string[] and add ToArray(), then everything will work.
In any case, I do not recommend using this library, I see the development of IPC in explicit code generation instead of IL code generation like here.

**Comment by Michael-Kempe** [comment]
Hi Konstantin, thanks for your response. And yes, I see that it's based on IL code generation.  Try to check for alternatives. Thanks.

**Comment by HavenDV** [comment]
I'm actively developing a SourceGenerator that generates client/server code based on a C# interface. I would be glad if you take a look at it (if you are still interested) and provide any feedback - https://github.com/HavenDV/H.Ipc
